server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: zuul-gateway.com
    prefer-ip-address: true 
    
zuul: 
  #ignored-services: microservicecloud-dept     #隐藏真实服务名称
  #prefix: /xtaro                               #统一公共前缀
  #ignored-services: "*"                        #全部隐藏
  routes: 
    mydept.serviceId: microservicecloud-dept  #映射真实服务名称
    mydept.path: /mydept/**
 
 
info: 
  app.name: xtaro-microservicecloud
  company.name: www.xtaro.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT   

